---
- name: Create environment directory
  ansible.builtin.file:
    path: "{{ esphome_conf_dir }}"
    state: directory
    mode: 02775
    owner: "{{ esphome_user }}"
    group: "{{ esphome_group }}"
    recurse: yes

- name: Create config directory
  ansible.builtin.file:
    path: "/home/{{ esphome_user }}/esphome/config/"
    state: directory
    mode: 02775
    owner: "{{ esphome_user }}"
    group: "{{ esphome_group }}"
    recurse: yes